name: Deploy Library Microservice to Kubernetes

on:
  push: 
    branches:
      - main

  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Authenticate with Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
          
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Initialize Terraform
        working-directory: ./scripts/terraform
        run: terraform init

      - name: Terraform plan - Show execution plan
        working-directory: ./scripts/terraform
        run: terraform plan

      - name: Terraform apply - Deploy resources
        working-directory: ./scripts/terraform
        run: terraform apply -auto-approve

      